import { ConnectionOptions, Job, Worker } from 'bullmq';
import { INVOICE_QUEUE_NAME, GenerateInvoiceJobData } from './invoiceQueue';
import { BillingService } from '../modules/billing/billing.service';
import { ConflictError } from '../common/errors/ApiError';
import { logger } from '../common/observability/logger';

export function createInvoiceWorker(
  connection: ConnectionOptions,
  billingService: BillingService
): Worker<GenerateInvoiceJobData> {
  return new Worker<GenerateInvoiceJobData>(
    INVOICE_QUEUE_NAME,
    async (job: Job<GenerateInvoiceJobData>) => {
      const { organizationId, periodStart, periodEnd } = job.data;
      try {
        const invoice = await billingService.generateInvoiceForPeriod(
          organizationId,
          new Date(periodStart),
          new Date(periodEnd)
        );
        logger.info({ organizationId, invoiceId: invoice.id }, 'Invoice generated by background worker');
        return { invoiceId: invoice.id, amountCents: invoice.amount_cents };
      } catch (err) {
        if (err instanceof ConflictError) {
          // An invoice for this period already exists -- not a failure,
          // just a no-op (e.g. the job was retried or double-enqueued).
          logger.info({ organizationId }, 'Invoice already exists for period, skipping');
          return { skipped: true };
        }
        throw err;
      }
    },
    { connection }
  );
}
